#Ashok Dhungana
#L6CG6
**Task1**

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

**Requirement**

1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.


Conversion Options:

1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
#Ashok Dhungana
#l6CG6
def length_conversion(value, unit):
    """
    Converts length between meters and feet.

    Parameters:
    value (float): The length value to be converted.
    unit (str): The unit of measurement ('m' for meters, 'ft' for feet).

    Returns:
    float: The converted length.
    """
    if unit == 'm':
        return value * 3.28084  # meters to feet
    elif unit == 'ft':
        return value / 3.28084  # feet to meters
    else:
        return ValueError("Unsupported length unit")


def weight_conversion(value, unit):
    """
    Converts weight between kilograms and pounds.

    Parameters:
    value (float): The weight value to be converted.
    unit (str): The unit of measurement ('kg' for kilograms, 'lbs' for pounds).

    Returns:
    float: The converted weight.
    """
    if unit == 'kg':
        return value * 2.20462  # kg to lbs
    elif unit == 'lbs':
        return value / 2.20462  # lbs to kg
    else:
        return ValueError("Unsupported weight unit")


def volume_conversion(value, unit):
    """
    Converts volume between liters and gallons.

    Parameters:
    value (float): The volume value to be converted.
    unit (str): The unit of measurement ('L' for liters, 'gal' for gallons).

    Returns:
    float: The converted volume.
    """
    if unit == 'L':
        return value * 0.264172  # liters to gallons
    elif unit == 'gal':
        return value / 0.264172  # gallons to liters
    else:
        return ValueError("Unsupported volume unit")


def main():
    """
    Main function to handle user input and perform unit conversions.

    It prompts the user to choose a conversion type (length, weight, or volume),
    asks for the value and unit, performs the conversion, and displays the result.
    """
    print("Welcome to the Unit Converter!")
    print("Choose a conversion type:")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kilograms <-> pounds)")
    print("3. Volume (liters <-> gallons)")

    try:
        choice = int(input("Enter 1, 2, or 3: "))
        value = float(input("Enter the value to be converted: "))

        if choice == 1:
            unit = input("Enter the unit (m for meters, ft for feet): ").strip().lower()
            converted_value = length_conversion(value, unit)
            print(f"Converted Value: {converted_value}")

        elif choice == 2:
            unit = input("Enter the unit (kg for kilograms, lbs for pounds): ").strip().lower()
            converted_value = weight_conversion(value, unit)
            print(f"Converted Value: {converted_value}")

        elif choice == 3:
            unit = input("Enter the unit (L for liters, gal for gallons): ").strip().lower()
            converted_value = volume_conversion(value, unit)
            print(f"Converted Value: {converted_value}")

        else:
            print("Invalid choice. Please select 1, 2, or 3.")

    except ValueError as e:
        print(f"Error: {e}. Please enter valid numerical values and units.")


if __name__ == "__main__":
    main()


Welcome to the Unit Converter!
Choose a conversion type:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Enter 1, 2, or 3: 3
Enter the value to be converted: 10
Enter the unit (L for liters, gal for gallons): gal
Converted Value: 37.854125342579835


**Ashok Dhungana**

**L6CG6**

**Task - 2**:

Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).


3. Perform the selected operation and display the result.

4. Handle potential errors, such as invalid input or empty lists.


**Requirements:**

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.


In [ ]:
#Ashok Dhungana
#L6CG6
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0  # Avoid division by zero

def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum value.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum value.
    """
    return min(numbers)

def main():
    """
    Main function to handle user input and perform mathematical operations on a list of numbers.

    It prompts the user to select an operation, takes input as a list of numbers, and displays the result.
    Handles invalid inputs gracefully.
    """
    print("Choose an operation:")
    print("1. Find Sum")
    print("2. Find Average")
    print("3. Find Maximum")
    print("4. Find Minimum")

    try:
        choice = int(input("Enter 1, 2, 3, or 4: "))

        # Get user input as a list of numbers
        numbers = input("Enter a list of numbers separated by spaces: ").strip().split()

        # Convert input strings to floats
        numbers = [float(num) for num in numbers]

        if not numbers:  # Check if list is empty
            raise ValueError("The list cannot be empty.")

        # Perform the chosen operation
        if choice == 1:
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif choice == 2:
            result = calculate_average(numbers)
            print(f"Average: {result}")
        elif choice == 3:
            result = find_maximum(numbers)
            print(f"Maximum: {result}")
        elif choice == 4:
            result = find_minimum(numbers)
            print(f"Minimum: {result}")
        else:
            print("Invalid choice. Please enter a number between 1 and 4.")

    except ValueError as e:
        print(f"Error: {e}. Please enter valid numbers.")

if __name__ == "__main__":
    main()





Choose an operation:
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Enter 1, 2, 3, or 4: 3
Enter a list of numbers separated by spaces: 1 2 3 4 5 6 7 8 9 
Maximum: 9.0


**4.2 Exercise on List Manipulation:**

**1. Extract Every Other Element:**

Write a Python function that extracts every other element from a list, starting from the first element.

**Requirements:**

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

**2. Slice a Sublist:**

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

 **Requirements:**

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

**3. Reverse a List Using Slicing:**
Write a Python function that reverses a list using slicing.


**Requirements**
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].




**4. Remove the First and Last Elements:**
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

 **Requirements:**

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

**5. Get the First n Elements:**

Write a Python function that extracts the first n elements from a list.

 **Requirements:**
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

**6. Extract Elements from the End:**
Write a Python function that extracts the last n elements of a list using slicing.

**Requirements:**
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

**7. Extract Elements in Reverse Order:**
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
 **Requirements:**
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
#Ashok Dhungana
#L6CG6
def extract_every_other(lst):
    """Returns a new list containing every other element from the original list."""
    return lst[::2]

def get_sublist(lst, start, end):
    """Returns a sublist from start to end (inclusive)."""
    return lst[start:end+1]

def reverse_list(lst):
    """Returns the reversed list using slicing."""
    return lst[::-1]

def remove_first_last(lst):
    """Returns a sublist without the first and last elements."""
    return lst[1:-1]

def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]

def get_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]

def reverse_skip(lst):
    """Returns a list of elements in reverse order, starting from the second-to-last element and skipping one element in between."""
    return lst[-2::-2]

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]

print("1. Extract Every Other Element:", extract_every_other(sample_list))
print("2. Slice a Sublist (2,4):", get_sublist(sample_list, 2, 4))
print("3. Reverse List:", reverse_list(sample_list))
print("4. Remove First and Last Elements:", remove_first_last(sample_list))
print("5. Get First 3 Elements:", get_first_n(sample_list, 3))
print("6. Get Last 2 Elements:", get_last_n(sample_list, 2))
print("7. Extract in Reverse Skipping One:", reverse_skip(sample_list))



1. Extract Every Other Element: [1, 3, 5]
2. Slice a Sublist (2,4): [3, 4, 5]
3. Reverse List: [6, 5, 4, 3, 2, 1]
4. Remove First and Last Elements: [2, 3, 4, 5]
5. Get First 3 Elements: [1, 2, 3]
6. Get Last 2 Elements: [5, 6]
7. Extract in Reverse Skipping One: [5, 3, 1]


**4.3 Exercise on Nested List**

**1. Flatten a Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

**Requirements:**

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

**2. Accessing Nested List Elements:**

Write a Python function that extracts a specific element from a nested list given its indices.

**Requirements:**

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

**3. Sum of All Elements in a Nested List:**
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

**Requirements:**

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

**4. Remove Specific Element from a Nested List:**

Write a Python function that removes all occurrences of a specific element from a nested list.

** Requirements:**

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

**5. Find the Maximum Element in a Nested List:**

Write a Python function that finds the maximum element in a nested list (regardless of depth).

 **Requirements:**

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.




**6. Count Occurrences of an Element in a Nested List:**

Write a Python function that counts how many times a specific element appears in a nested list.

**Requirements:**

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

**7. Flatten a List of Lists of Lists:**

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.


** Requirements:**

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

**8. Nested List Average:**

Write a Python function that calculates the average of all elements in a nested list.
 **Requirements:**

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
#Ashok Dhungana
#L6CG6

def flatten(lst):
    """Flattens a nested list into a single list."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def access_nested_element(lst, indices):
    """Extracts a specific element from a nested list given its indices."""
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    """Calculates the sum of all elements in a nested list."""
    return sum(flatten(lst))

def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    if isinstance(lst, list):
        return [remove_element(sub, elem) for sub in lst if sub != elem]
    else:
        return lst

def find_max(lst):
    """Finds the maximum element in a nested list."""
    return max(flatten(lst))

def count_occurrences(lst, elem):
    """Counts occurrences of an element in a nested list."""
    return flatten(lst).count(elem)

def deep_flatten(lst):
    """Flattens a deeply nested list into a single list."""
    if isinstance(lst, Iterable) and not isinstance(lst, (str, bytes)):
        return [a for i in lst for a in deep_flatten(i)]
    else:
        return [lst]

def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

nested_list = [[1, 2], [3, 4], [5]]
deep_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
test_list = [[1, 2], [3, [4, 5]], 6]

print("1. Flatten a Nested List:", flatten(nested_list))
print("2. Access Nested Element (1,2):", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print("3. Sum of Nested List:", sum_nested(test_list))
print("4. Remove Element (2):", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("5. Find Maximum Element:", find_max(test_list))
print("6. Count Occurrences of 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("7. Deep Flatten:", deep_flatten(deep_list))
print("8. Average of Nested List:", average_nested([[1, 2], [3, 4], [5, 6]]))


1. Flatten a Nested List: [1, 2, 3, 4, 5]
2. Access Nested Element (1,2): 6
3. Sum of Nested List: 21
4. Remove Element (2): [[1], [3], [4, 5]]
5. Find Maximum Element: 6
6. Count Occurrences of 2: 3
7. Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average of Nested List: 3.5


**10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
#Ashok Dhungana
#L6CG6

import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 Array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All-One 4x2 Array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with a specific value (e.g., 7)
fill_array = np.full((3, 3), 7)
print("\n3. Array filled with 7:\n", fill_array)

# 4. Return a new array of zeros with the same shape and type as a given array
sample_array = np.array([[1, 2, 3], [4, 5, 6]])  # Example array
zeros_like_array = np.zeros_like(sample_array)
print("\n4. Zeros Array with Same Shape as sample_array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(sample_array)
print("\n5. Ones Array with Same Shape as sample_array:\n", ones_like_array)

# 6. Convert an existing list [1, 2, 3, 4] to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy Array from List:\n", numpy_array)



1. Empty 2x2 Array:
 [[4.64712835e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]

2. All-One 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Array with Same Shape as sample_array:
 [[0 0 0]
 [0 0 0]]

5. Ones Array with Same Shape as sample_array:
 [[1 1 1]
 [1 1 1]]

6. Converted NumPy Array from List:
 [1 2 3 4]


**Problem - 2: Array Manipulation:Numerical Ranges and Array indexing:**

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
#Ashok Dhungana
#L6CG6
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", array_10_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_0_8 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix from 0 to 8:\n", matrix_0_8)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find its mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random Array Mean:\n", mean_value)

# 5. Create a 10x10 array with random values and find min & max values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. Min & Max of 10x10 Random Array:\nMin:", min_value, "Max:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Replacing the 5th element (index 4) with 1
print("\n6. Zero Array with 5th Element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D Array with 1s on Border and 0s Inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard Pattern:\n", checkerboard)


1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random Array Mean:
 0.5424240217311674

5. Min & Max of 10x10 Random Array:
Min: 0.012434101302684186 Max: 0.9864839405416512

6. Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed Array:
 [0 4 0 0 2 1]

8. 2D Array with 1s on Border and 0s Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
#Ashok Dhungana
#L6CG6
import numpy as np

# Given Arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("1. Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
subtract_xy = x - y
print("\n2. Subtraction of x and y:\n", subtract_xy)

# 3. Multiply the array with any integer (e.g., multiply x by 3)
multiply_x = x * 3
print("\n3. Multiplication of x by 3:\n", multiply_x)

# 4. Find the square of each element in the array x
square_x = np.square(x)
print("\n4. Square of elements in x:\n", square_x)

# 5. Dot product between v and w, x and v, x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\n5. Dot Product:")
print("   v . w =", dot_vw)
print("   x . v =\n", dot_xv)
print("   x . y =\n", dot_xy)

# 6. Concatenate x and y along rows, and concatenate v and w along columns
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))

print("\n6. Concatenation of x and y along rows:\n", concat_xy)
print("\n   Concatenation of v and w along columns:\n", concat_vw)

# 7. Attempt to concatenate x and v (will cause an error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\n7. ERROR: Cannot concatenate x and v!")
    print("   Reason:", e)


1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]

4. Square of elements in x:
 [[ 1  4]
 [ 9 25]]

5. Dot Product:
   v . w = 219
   x . v =
 [29 77]
   x . y =
 [[19 22]
 [50 58]]

6. Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

   Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

7. ERROR: Cannot concatenate x and v!
   Reason: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem - 4: Matrix Operations:**

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
import numpy as np

import numpy as np

# Given Matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^(-1) = I
A_inv = np.linalg.inv(A)  # Compute inverse of A
identity_matrix = np.dot(A, A_inv)  # A * A^(-1)

print("1. A * A^(-1) = Identity Matrix:\n", np.round(identity_matrix, 3))  # Round to 3 decimal places

# 2. Prove AB ≠ BA
AB = np.dot(A, B)  # Matrix multiplication AB
BA = np.dot(B, A)  # Matrix multiplication BA

print("\n2. Matrix Multiplication Check (AB ≠ BA):\n AB:\n", AB, "\n BA:\n", BA)
print("   Are AB and BA equal? ", np.array_equal(AB, BA))  # Check equality

# 3. Prove (AB)^T = B^T * A^T
AB_transpose = np.transpose(AB)  # Transpose of (AB)
BT_AT = np.dot(B.T, A.T)  # B^T * A^T

print("\n3. Transpose Property (AB)^T = B^T * A^T:\n (AB)^T:\n", AB_transpose, "\n B^T * A^T:\n", BT_AT)
print("   Are (AB)^T and B^T * A^T equal? ", np.array_equal(AB_transpose, BT_AT))


1. A * A^(-1) = Identity Matrix:
 [[1. 0.]
 [0. 1.]]

2. Matrix Multiplication Check (AB ≠ BA):
 AB:
 [[23 13]
 [51 29]] 
 BA:
 [[36 44]
 [13 16]]
   Are AB and BA equal?  False

3. Transpose Property (AB)^T = B^T * A^T:
 (AB)^T:
 [[23 51]
 [13 29]] 
 B^T * A^T:
 [[23 51]
 [13 29]]
   Are (AB)^T and B^T * A^T equal?  True


In [ ]:
#Ashok Dhungana
#L6CG6
# Define coefficient matrix A and constant matrix B
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

# Solve for X using inverse method: X = A^(-1) * B
A_inv = np.linalg.inv(A_matrix)  # Compute inverse of A
X = np.dot(A_inv, B_matrix)  # Solve for X

print("\n4. Solution to the Linear Equations using Inverse Method:\n x =", X[0], ", y =", X[1], ", z =", X[2])



4. Solution to the Linear Equations using Inverse Method:
 x = 2.0 , y = 1.0 , z = -2.0


**10.2 Experiment: How Fast is Numpy?**

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

**1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.


**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.


**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

**4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
#Ashok Dhungana
#L6CG6
import numpy as np
import time

# Set size for 1D operations
size = 1_000_000

# Generate random data
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
array1 = np.arange(size)
array2 = np.arange(size)

### 1. Element-wise Addition ###

# Using Python Lists
start_time = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print(f"1. Element-wise Addition (Python List): {end_time - start_time:.5f} sec")

# Using NumPy Arrays
start_time = time.time()
array_add = array1 + array2
end_time = time.time()
print(f"   Element-wise Addition (NumPy): {end_time - start_time:.5f} sec\n")


### 2. Element-wise Multiplication ###

# Using Python Lists
start_time = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"2. Element-wise Multiplication (Python List): {end_time - start_time:.5f} sec")

# Using NumPy Arrays
start_time = time.time()
array_mul = array1 * array2
end_time = time.time()
print(f"   Element-wise Multiplication (NumPy): {end_time - start_time:.5f} sec\n")


### 3. Dot Product ###

# Using Python Lists
start_time = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print(f"3. Dot Product (Python List): {end_time - start_time:.5f} sec")

# Using NumPy Arrays
start_time = time.time()
array_dot = np.dot(array1, array2)
end_time = time.time()
print(f"   Dot Product (NumPy): {end_time - start_time:.5f} sec\n")


### 4. Matrix Multiplication ###

# Set size for 2D operations
matrix_size = 1000

# Generate random matrices
matrix_list1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix_list2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix_array1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
matrix_array2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

# Using Python Lists
start_time = time.time()
matrix_result = [[sum(a*b for a, b in zip(row, col)) for col in zip(*matrix_list2)] for row in matrix_list1]
end_time = time.time()
print(f"4. Matrix Multiplication (Python List): {end_time - start_time:.5f} sec")

# Using NumPy Arrays
start_time = time.time()
matrix_result_np = np.dot(matrix_array1, matrix_array2)
end_time = time.time()
print(f"   Matrix Multiplication (NumPy): {end_time - start_time:.5f} sec")


1. Element-wise Addition (Python List): 0.08549 sec
   Element-wise Addition (NumPy): 0.00508 sec

2. Element-wise Multiplication (Python List): 0.11764 sec
   Element-wise Multiplication (NumPy): 0.01001 sec

3. Dot Product (Python List): 0.09766 sec
   Dot Product (NumPy): 0.00197 sec

4. Matrix Multiplication (Python List): 175.69676 sec
   Matrix Multiplication (NumPy): 2.00717 sec
